name: Java CI

# 检测到 src 文件内 .java 文件有变动执行编译
on:
  push:
    paths:
      - '**/*src/**/*.java'

jobs:
  build:
#	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
# 下载代码
    - uses: actions/checkout@v3
    - name: Set up JDK 8
# 安装 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
# Gradlew 打包 
    - name: Build Jar
      run: |
        chmod -R 777 ./gradlew
        chmod 777 ./gradlew
        ./gradlew
# 将打包好的 Jar 包 放到 build 文件夹
    - run: mkdir autobuild && cp /gradle/wrapper/*.jar autobuild
# 上传文件并发布 Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        prerelease: false
        title: "Release ${{ env.RELEASE_VERSION }}"
        files: |
          autobuild/*.jar
